services:
  - type: web
    name: health-info-system
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn health_system.wsgi:application 
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "health-info-system-djja.onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
      - key: PYTHON_VERSION
        value: 3.10.0
    disk:
      name: sqlite
      mountPath: /opt/render/project/src
      sizeGB: 1